parameters:
- name: ros_metapackage  # Deprecated
  type: string
  default: 'ros-humble-desktop'
- name: rosdistro
  type: string
  default: 'humble'
- name: metapackage
  type: string
  default: 'desktop'
- name: custom_version
  type: string
  default: 'latest'
- name: custom_test_target
  type: string
  default: 'run_tests'
- name: custom_test_timeout
  type: number
  default: 15
- name: pre_build  # Hook to run immediately before catkin_make.
  type: stepList
  default: []
- name: build_chocolatey_pkg  # Only supported for Windows build.
  type: boolean
  default: false
- name: platforms
  type: object
  default:
    - linux

jobs:
- ${{ if containsValue(parameters.platforms, 'linux') }}:
  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-22.04'
    container: 'osrf/ros2:devel'
    timeoutInMinutes: 240
    variables:
      CI_ROSDISTRO: '${{ parameters.rosdistro }}'
      CI_METAPACKAGE: '${{ parameters.metapackage }}'
    steps:
    - checkout: self
      submodules: recursive

    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.StagingDirectory)/src/_'

    - script: |
        source /opt/ros/$CI_ROSDISTRO/setup.sh
        sudo apt update
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
      displayName: Install prerequisites
      workingDirectory: '$(Build.StagingDirectory)'

  
